"""
TextTransformer — applies rule-based and statistical transformations to make
AI-generated text sound more natural. This is the main processing engine.

Passes (in order):
  1. passive_rewrites  — "it can be seen that" → "we can see that"
  2. formal_simplify   — verbose phrases, formal verbs/nouns → casual
  3. contractions      — "do not" → "don't", "it is" → "it's", etc.
  4. sentence_variety  — inject casual openers into monotonous sentences
"""

import re
import random
import logging
from typing import List, Tuple

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Contraction map
# ---------------------------------------------------------------------------
_CONTRACTION_EXPAND = {
    # to be
    r"\bit is\b":       "it's",
    r"\bIt is\b":       "It's",
    r"\bthat is\b":     "that's",
    r"\bThat is\b":     "That's",
    r"\bwhat is\b":     "what's",
    r"\bWhat is\b":     "What's",
    r"\bwho is\b":      "who's",
    r"\bWho is\b":      "Who's",
    r"\bhere is\b":     "here's",
    r"\bHere is\b":     "Here's",
    r"\bthere is\b":    "there's",
    r"\bThere is\b":    "There's",
    r"\bwhere is\b":    "where's",
    r"\bWhere is\b":    "Where's",
    r"\bhow is\b":      "how's",
    r"\bHow is\b":      "How's",
    r"\bthat will\b":   "that'll",
    r"\bThat will\b":   "That'll",
    r"\bwhat will\b":   "what'll",
    r"\bWhat will\b":   "What'll",
    r"\bthere will\b":  "there'll",
    r"\bThere will\b":  "There'll",
    r"\bthere are\b":   "there're",
    r"\bThere are\b":   "There're",
    r"\bthese are\b":   "these're",
    r"\bThese are\b":   "These're",
    # I
    r"\bI am\b":        "I'm",
    r"\bI will\b":      "I'll",
    r"\bI would\b":     "I'd",
    r"\bI have\b":      "I've",
    r"\bI had\b":       "I'd",
    # we
    r"\bwe are\b":      "we're",
    r"\bWe are\b":      "We're",
    r"\bwe will\b":     "we'll",
    r"\bWe will\b":     "We'll",
    r"\bwe have\b":     "we've",
    r"\bWe have\b":     "We've",
    r"\bwe would\b":    "we'd",
    r"\bWe would\b":    "We'd",
    r"\bwe had\b":      "we'd",
    r"\bWe had\b":      "We'd",
    # you
    r"\byou are\b":     "you're",
    r"\bYou are\b":     "You're",
    r"\byou will\b":    "you'll",
    r"\bYou will\b":    "You'll",
    r"\byou have\b":    "you've",
    r"\bYou have\b":    "You've",
    r"\byou would\b":   "you'd",
    r"\bYou would\b":   "You'd",
    r"\byou had\b":     "you'd",
    r"\bYou had\b":     "You'd",
    # they
    r"\bthey are\b":    "they're",
    r"\bThey are\b":    "They're",
    r"\bthey will\b":   "they'll",
    r"\bThey will\b":   "They'll",
    r"\bthey have\b":   "they've",
    r"\bThey have\b":   "They've",
    r"\bthey would\b":  "they'd",
    r"\bThey would\b":  "They'd",
    r"\bthey had\b":    "they'd",
    r"\bThey had\b":    "They'd",
    # he / she
    r"\bhe is\b":       "he's",
    r"\bHe is\b":       "He's",
    r"\bhe will\b":     "he'll",
    r"\bHe will\b":     "He'll",
    r"\bhe would\b":    "he'd",
    r"\bHe would\b":    "He'd",
    r"\bhe has\b":      "he's",
    r"\bHe has\b":      "He's",
    r"\bhe had\b":      "he'd",
    r"\bHe had\b":      "He'd",
    r"\bshe is\b":      "she's",
    r"\bShe is\b":      "She's",
    r"\bshe will\b":    "she'll",
    r"\bShe will\b":    "She'll",
    r"\bshe would\b":   "she'd",
    r"\bShe would\b":   "She'd",
    r"\bshe has\b":     "she's",
    r"\bShe has\b":     "She's",
    r"\bshe had\b":     "she'd",
    r"\bShe had\b":     "She'd",
    # it
    r"\bit will\b":     "it'll",
    r"\bIt will\b":     "It'll",
    r"\bit would\b":    "it'd",
    r"\bIt would\b":    "It'd",
    r"\bit has\b":      "it's",
    r"\bIt has\b":      "It's",
    r"\bit had\b":      "it'd",
    r"\bIt had\b":      "It'd",
    # that / who / which
    r"\bthat would\b":  "that'd",
    r"\bThat would\b":  "That'd",
    r"\bthat have\b":   "that've",
    r"\bThat have\b":   "That've",
    r"\bwho will\b":    "who'll",
    r"\bWho will\b":    "Who'll",
    r"\bwho would\b":   "who'd",
    r"\bWho would\b":   "Who'd",
    r"\bwho have\b":    "who've",
    r"\bWho have\b":    "Who've",
    # negatives
    r"\bdo not\b":      "don't",
    r"\bDo not\b":      "Don't",
    r"\bdoes not\b":    "doesn't",
    r"\bDoes not\b":    "Doesn't",
    r"\bdid not\b":     "didn't",
    r"\bDid not\b":     "Didn't",
    r"\bcannot\b":      "can't",
    r"\bCannot\b":      "Can't",
    r"\bcould not\b":   "couldn't",
    r"\bCould not\b":   "Couldn't",
    r"\bwould not\b":   "wouldn't",
    r"\bWould not\b":   "Wouldn't",
    r"\bshould not\b":  "shouldn't",
    r"\bShould not\b":  "Shouldn't",
    r"\bwill not\b":    "won't",
    r"\bWill not\b":    "Won't",
    r"\bmust not\b":    "mustn't",
    r"\bMust not\b":    "Mustn't",
    r"\bneed not\b":    "needn't",
    r"\bNeed not\b":    "Needn't",
    r"\bis not\b":      "isn't",
    r"\bIs not\b":      "Isn't",
    r"\bare not\b":     "aren't",
    r"\bAre not\b":     "Aren't",
    r"\bwas not\b":     "wasn't",
    r"\bWas not\b":     "Wasn't",
    r"\bwere not\b":    "weren't",
    r"\bWere not\b":    "Weren't",
    r"\bhave not\b":    "haven't",
    r"\bHave not\b":    "Haven't",
    r"\bhas not\b":     "hasn't",
    r"\bHas not\b":     "Hasn't",
    r"\bhad not\b":     "hadn't",
    r"\bHad not\b":     "Hadn't",
    r"\bmight not\b":   "mightn't",
    r"\bMight not\b":   "Mightn't",
    r"\bdare not\b":    "daren't",
    r"\bDare not\b":    "Daren't",
    r"\bought not\b":   "oughtn't",
    r"\bOught not\b":   "Oughtn't",
    # misc
    r"\blet us\b":      "let's",
    r"\bLet us\b":      "Let's",
    r"\bcome on\b":     "c'mon",
    r"\bCome on\b":     "C'mon",
    r"\bgoing to\b":    "gonna",
    r"\bGoing to\b":    "Gonna",
    r"\bwant to\b":     "wanna",
    r"\bWant to\b":     "Wanna",
    r"\bkind of\b":     "kinda",
    r"\bKind of\b":     "Kinda",
    r"\bout of\b":      "outta",
    r"\bOut of\b":      "Outta",
    r"\bsort of\b":     "sorta",
    r"\bSort of\b":     "Sorta",
}

# ---------------------------------------------------------------------------
# Formal → casual phrase substitutions
# Longer / more specific patterns come first to avoid partial matches.
# ---------------------------------------------------------------------------
_FORMAL_TO_CASUAL: List[Tuple[str, str]] = [
    # -----------------------------------------------------------------------
    # Transition words & connectors
    # -----------------------------------------------------------------------
    (r"\bIn conclusion,?\b",                        "To wrap up,"),
    (r"\bTo summarize,?\b",                         "In short,"),
    (r"\bTo conclude,?\b",                          "To wrap up,"),
    (r"\bIn summary,?\b",                           "In short,"),
    (r"\bFurthermore,?\b",                          "On top of that,"),
    (r"\bMoreover,?\b",                             "Plus,"),
    (r"\bIn addition,?\b",                          "Also,"),
    (r"\bAdditionally,?\b",                         "Also,"),
    (r"\bSubsequently,?\b",                         "Then,"),
    (r"\bConversely,?\b",                           "On the flip side,"),
    (r"\bNevertheless,?\b",                         "Still,"),
    (r"\bNonetheless,?\b",                          "Still,"),
    (r"\bHowever,?\b",                              "That said,"),
    (r"\bConsequently,?\b",                         "So,"),
    (r"\bTherefore,?\b",                            "So,"),
    (r"\bThus,?\b",                                 "So,"),
    (r"\bHence,?\b",                                "Which is why"),
    (r"\bAccordingly,?\b",                          "So,"),
    (r"\bNotwithstanding,?\b",                      "Even so,"),
    (r"\bIn contrast,?\b",                          "On the other hand,"),
    (r"\bBy contrast,?\b",                          "Compared to that,"),
    (r"\bIn comparison,?\b",                        "Compared to that,"),
    (r"\bIn particular,?\b",                        "Specifically,"),
    (r"\bSpecifically speaking,?\b",                "Specifically,"),
    (r"\bTo illustrate,?\b",                        "For example,"),
    (r"\bFor instance,?\b",                         "For example,"),
    (r"\bNamely,?\b",                               "That is,"),
    (r"\bTo elaborate,?\b",                         "To dig into that,"),
    (r"\bIn other words,?\b",                       "Put simply,"),
    (r"\bThat is to say,?\b",                       "Put simply,"),
    (r"\bTo put it differently,?\b",                "Put another way,"),
    (r"\bTo put it another way,?\b",                "Put another way,"),
    (r"\bTo be more precise,?\b",                   "More precisely,"),
    (r"\bTo be specific,?\b",                       "Specifically,"),
    (r"\bOn the contrary,?\b",                      "Actually,"),
    (r"\bIn spite of this,?\b",                     "Even so,"),
    (r"\bDespite this,?\b",                         "Even so,"),
    (r"\bWith that said,?\b",                       "That said,"),
    (r"\bHaving said that,?\b",                     "That said,"),
    (r"\bAll things considered,?\b",                "All in all,"),
    (r"\bOn balance,?\b",                           "Overall,"),
    (r"\bTaking everything into account,?\b",       "All things considered,"),
    (r"\bIn light of this,?\b",                     "Given that,"),
    (r"\bIn view of this,?\b",                      "Given that,"),
    (r"\bIn any case,?\b",                          "Either way,"),
    (r"\bIn any event,?\b",                         "Either way,"),
    (r"\bRegardless,?\b",                           "Either way,"),
    (r"\bFirst and foremost,?\b",                   "First off,"),
    (r"\bFirst of all,?\b",                         "First off,"),
    (r"\bLast but not least,?\b",                   "And finally,"),
    (r"\bTo begin with,?\b",                        "For starters,"),
    (r"\bTo start with,?\b",                        "For starters,"),

    # -----------------------------------------------------------------------
    # Filler openings & hedges
    # -----------------------------------------------------------------------
    (r"\bIt is important to note that\b",           "Worth noting:"),
    (r"\bIt is worth noting that\b",                "Worth noting:"),
    (r"\bIt should be noted that\b",                "Note that"),
    (r"\bIt is worth mentioning that\b",            "Interestingly,"),
    (r"\bIt is crucial to understand that\b",       "The key thing is"),
    (r"\bIt is essential to recognize that\b",      "Keep in mind that"),
    (r"\bIt is essential to understand that\b",     "Keep in mind that"),
    (r"\bIt is important to understand that\b",     "Keep in mind that"),
    (r"\bIt is important to remember that\b",       "Don't forget that"),
    (r"\bIt is vital to note that\b",               "Importantly,"),
    (r"\bIt is evident that\b",                     "Clearly,"),
    (r"\bIt is clear that\b",                       "Clearly,"),
    (r"\bIt is obvious that\b",                     "Obviously,"),
    (r"\bIt is widely known that\b",                "Most people know that"),
    (r"\bIt goes without saying that\b",            "Obviously,"),
    (r"\bNeedless to say,?\b",                      "Obviously,"),
    (r"\bAs previously mentioned,?\b",              "As I said,"),
    (r"\bAs mentioned above,?\b",                   "As I said,"),
    (r"\bAs stated earlier,?\b",                    "As I said,"),
    (r"\bAs discussed above,?\b",                   "As I mentioned,"),
    (r"\bAs outlined above,?\b",                    "As I covered,"),
    (r"\bAs we can see,?\b",                        "Clearly,"),
    (r"\bAs noted above,?\b",                       "As I mentioned,"),
    (r"\bAs demonstrated above,?\b",                "As shown above,"),
    (r"\bAs we have seen,?\b",                      "As we've seen,"),
    (r"\bAs one might expect,?\b",                  "Unsurprisingly,"),
    (r"\bAs one can imagine,?\b",                   "Unsurprisingly,"),
    (r"\bIt is worth emphasizing that\b",           "Worth stressing:"),
    (r"\bIt is worth highlighting that\b",          "Worth highlighting:"),
    (r"\bIt is interesting to note that\b",         "Interestingly,"),
    (r"\bIt is fascinating to note that\b",         "Fascinatingly,"),
    (r"\bIt is remarkable that\b",                  "Remarkably,"),
    (r"\bIt is noteworthy that\b",                  "Notably,"),
    (r"\bIt cannot be denied that\b",               "Clearly,"),
    (r"\bThere is no doubt that\b",                 "Clearly,"),
    (r"\bThere is no question that\b",              "Clearly,"),
    (r"\bSuffice it to say,?\b",                    "Simply put,"),
    (r"\bLet it be noted that\b",                   "Note that"),
    (r"\bBear in mind that\b",                      "Keep in mind that"),
    (r"\bIt must be acknowledged that\b",           "To be fair,"),
    (r"\bOne must acknowledge that\b",              "To be fair,"),
    (r"\bOne must consider that\b",                 "Worth considering:"),
    (r"\bOne should note that\b",                   "Note that"),
    (r"\bOne can argue that\b",                     "You could argue that"),
    (r"\bOne could argue that\b",                   "You could argue that"),

    # -----------------------------------------------------------------------
    # Verbose constructions
    # -----------------------------------------------------------------------
    (r"\bIn order to\b",                            "To"),
    (r"\bin order to\b",                            "to"),
    (r"\bdue to the fact that\b",                   "because"),
    (r"\bDue to the fact that\b",                   "Because"),
    (r"\bin light of the fact that\b",              "since"),
    (r"\bIn light of the fact that\b",              "Since"),
    (r"\bfor the purpose of\b",                     "to"),
    (r"\bFor the purpose of\b",                     "To"),
    (r"\bwith the intention of\b",                  "to"),
    (r"\bWith the intention of\b",                  "To"),
    (r"\bwith the aim of\b",                        "to"),
    (r"\bWith the aim of\b",                        "To"),
    (r"\bwith the goal of\b",                       "to"),
    (r"\bWith the goal of\b",                       "To"),
    (r"\bwith the objective of\b",                  "to"),
    (r"\bWith the objective of\b",                  "To"),
    (r"\bat this point in time\b",                  "now"),
    (r"\bAt this point in time\b",                  "Now"),
    (r"\bat the present time\b",                    "currently"),
    (r"\bAt the present time\b",                    "Currently"),
    (r"\bat the current time\b",                    "currently"),
    (r"\bAt the current time\b",                    "Currently"),
    (r"\bat this moment in time\b",                 "right now"),
    (r"\bAt this moment in time\b",                 "Right now"),
    (r"\bin the near future\b",                     "soon"),
    (r"\bIn the near future\b",                     "Soon"),
    (r"\bin the foreseeable future\b",              "going forward"),
    (r"\bIn the foreseeable future\b",              "Going forward"),
    (r"\bin the not too distant future\b",          "before long"),
    (r"\bIn the not too distant future\b",          "Before long"),
    (r"\bon a daily basis\b",                       "every day"),
    (r"\bOn a daily basis\b",                       "Every day"),
    (r"\bon a regular basis\b",                     "regularly"),
    (r"\bOn a regular basis\b",                     "Regularly"),
    (r"\bon a consistent basis\b",                  "consistently"),
    (r"\bOn a consistent basis\b",                  "Consistently"),
    (r"\bon a weekly basis\b",                      "every week"),
    (r"\bOn a weekly basis\b",                      "Every week"),
    (r"\bprior to\b",                               "before"),
    (r"\bPrior to\b",                               "Before"),
    (r"\bsubsequent to\b",                          "after"),
    (r"\bSubsequent to\b",                          "After"),
    (r"\bwith regard to\b",                         "about"),
    (r"\bWith regard to\b",                         "About"),
    (r"\bwith respect to\b",                        "about"),
    (r"\bWith respect to\b",                        "About"),
    (r"\bin terms of\b",                            "for"),
    (r"\bIn terms of\b",                            "For"),
    (r"\bfor the most part\b",                      "mostly"),
    (r"\bFor the most part\b",                      "Mostly"),
    (r"\bto a certain extent\b",                    "somewhat"),
    (r"\bTo a certain extent\b",                    "Somewhat"),
    (r"\bto a large extent\b",                      "largely"),
    (r"\bTo a large extent\b",                      "Largely"),
    (r"\bto a great extent\b",                      "largely"),
    (r"\bTo a great extent\b",                      "Largely"),
    (r"\bto some extent\b",                         "somewhat"),
    (r"\bTo some extent\b",                         "Somewhat"),
    (r"\ba large number of\b",                      "many"),
    (r"\bA large number of\b",                      "Many"),
    (r"\ba significant number of\b",                "many"),
    (r"\bA significant number of\b",                "Many"),
    (r"\ba considerable number of\b",               "quite a few"),
    (r"\bA considerable number of\b",               "Quite a few"),
    (r"\ba great number of\b",                      "a lot of"),
    (r"\bA great number of\b",                      "A lot of"),
    (r"\ba majority of\b",                          "most"),
    (r"\bA majority of\b",                          "Most"),
    (r"\bthe majority of\b",                        "most"),
    (r"\bThe majority of\b",                        "Most"),
    (r"\bthe vast majority of\b",                   "most"),
    (r"\bThe vast majority of\b",                   "Most"),
    (r"\ba wide variety of\b",                      "many kinds of"),
    (r"\bA wide variety of\b",                      "Many kinds of"),
    (r"\ba wide range of\b",                        "all sorts of"),
    (r"\bA wide range of\b",                        "All sorts of"),
    (r"\ba broad range of\b",                       "all sorts of"),
    (r"\bA broad range of\b",                       "All sorts of"),
    (r"\bplay a crucial role in\b",                 "directly affect"),
    (r"\bplay an important role in\b",              "matter for"),
    (r"\bplay a significant role in\b",             "significantly affect"),
    (r"\bplay a key role in\b",                     "be key to"),
    (r"\bplay a role in\b",                         "affect"),
    (r"\bhas the ability to\b",                     "can"),
    (r"\bHas the ability to\b",                     "Can"),
    (r"\bhave the ability to\b",                    "can"),
    (r"\bHave the ability to\b",                    "Can"),
    (r"\bis able to\b",                             "can"),
    (r"\bIs able to\b",                             "Can"),
    (r"\bare able to\b",                            "can"),
    (r"\bAre able to\b",                            "Can"),
    (r"\bwas able to\b",                            "could"),
    (r"\bWas able to\b",                            "Could"),
    (r"\bwere able to\b",                           "could"),
    (r"\bWere able to\b",                           "Could"),
    (r"\bin the event that\b",                      "if"),
    (r"\bIn the event that\b",                      "If"),
    (r"\bin the case that\b",                       "if"),
    (r"\bIn the case that\b",                       "If"),
    (r"\bin the case of\b",                         "for"),
    (r"\bIn the case of\b",                         "For"),
    (r"\bunder the circumstances\b",                "given the situation"),
    (r"\bUnder the circumstances\b",                "Given the situation"),
    (r"\bunder no circumstances\b",                 "never"),
    (r"\bUnder no circumstances\b",                 "Never"),
    (r"\bfor the reason that\b",                    "because"),
    (r"\bFor the reason that\b",                    "Because"),
    (r"\bgiven the fact that\b",                    "since"),
    (r"\bGiven the fact that\b",                    "Since"),
    (r"\bon the grounds that\b",                    "because"),
    (r"\bOn the grounds that\b",                    "Because"),
    (r"\bowing to the fact that\b",                 "because"),
    (r"\bOwing to the fact that\b",                 "Because"),
    (r"\bfor all intents and purposes\b",           "basically"),
    (r"\bFor all intents and purposes\b",           "Basically"),
    (r"\bby means of\b",                            "using"),
    (r"\bBy means of\b",                            "Using"),
    (r"\bby virtue of\b",                           "because of"),
    (r"\bBy virtue of\b",                           "Because of"),
    (r"\bby way of\b",                              "via"),
    (r"\bBy way of\b",                              "Via"),
    (r"\bwith a view to\b",                         "to"),
    (r"\bWith a view to\b",                         "To"),
    (r"\bwith reference to\b",                      "about"),
    (r"\bWith reference to\b",                      "About"),
    (r"\bin relation to\b",                         "about"),
    (r"\bIn relation to\b",                         "About"),
    (r"\bin connection with\b",                     "about"),
    (r"\bIn connection with\b",                     "About"),
    (r"\bin accordance with\b",                     "following"),
    (r"\bIn accordance with\b",                     "Following"),
    (r"\bin compliance with\b",                     "following"),
    (r"\bIn compliance with\b",                     "Following"),
    (r"\bin conjunction with\b",                    "along with"),
    (r"\bIn conjunction with\b",                    "Along with"),
    (r"\bin the context of\b",                      "when it comes to"),
    (r"\bIn the context of\b",                      "When it comes to"),
    (r"\bin the realm of\b",                        "in"),
    (r"\bIn the realm of\b",                        "In"),
    (r"\bin the field of\b",                        "in"),
    (r"\bIn the field of\b",                        "In"),
    (r"\bin the area of\b",                         "in"),
    (r"\bIn the area of\b",                         "In"),
    (r"\bin the domain of\b",                       "in"),
    (r"\bIn the domain of\b",                       "In"),
    (r"\bin the sphere of\b",                       "in"),
    (r"\bIn the sphere of\b",                       "In"),
    (r"\bin the world of\b",                        "in"),
    (r"\bIn the world of\b",                        "In"),
    (r"\bfrom the perspective of\b",                "for"),
    (r"\bFrom the perspective of\b",                "For"),
    (r"\bfrom the standpoint of\b",                 "for"),
    (r"\bFrom the standpoint of\b",                 "For"),
    (r"\bfrom the point of view of\b",              "for"),
    (r"\bFrom the point of view of\b",              "For"),
    (r"\bfrom a [a-z]+ perspective\b",              ""),   # "from a business perspective" → ""
    (r"\bit should also be noted that\b",           "also,"),
    (r"\bIt should also be noted that\b",           "Also,"),
    (r"\bthe fact that\b",                          "that"),
    (r"\bThe fact that\b",                          "That"),
    (r"\bgiven that\b",                             "since"),
    (r"\bGiven that\b",                             "Since"),
    (r"\bso as to\b",                               "to"),
    (r"\bSo as to\b",                               "To"),
    (r"\bsuch that\b",                              "so that"),
    (r"\bSuch that\b",                              "So that"),

    # -----------------------------------------------------------------------
    # Formal verbs → casual
    # -----------------------------------------------------------------------
    (r"\bUtilize\b",            "use"),
    (r"\butilize\b",            "use"),
    (r"\bFacilitate\b",         "help"),
    (r"\bfacilitate\b",         "help"),
    (r"\bDemonstrate\b",        "show"),
    (r"\bdemonstrate\b",        "show"),
    (r"\bAssist\b",             "help"),
    (r"\bassist\b",             "help"),
    (r"\bObtain\b",             "get"),
    (r"\bobtain\b",             "get"),
    (r"\bPurchase\b",           "buy"),
    (r"\bpurchase\b",           "buy"),
    (r"\bProvide\b",            "give"),
    (r"\bprovide\b",            "give"),
    (r"\bRequire\b",            "need"),
    (r"\brequire\b",            "need"),
    (r"\bAttempt\b",            "try"),
    (r"\battempt\b",            "try"),
    (r"\bCommence\b",           "start"),
    (r"\bcommence\b",           "start"),
    (r"\bTerminate\b",          "end"),
    (r"\bterminate\b",          "end"),
    (r"\bAscertain\b",          "find out"),
    (r"\bascertain\b",          "find out"),
    (r"\bEnhance\b",            "improve"),
    (r"\benhance\b",            "improve"),
    (r"\bImplement\b",          "use"),
    (r"\bimplement\b",          "use"),
    (r"\bLeverage\b",           "use"),
    (r"\bleverage\b",           "use"),
    (r"\bMaximize\b",           "get the most out of"),
    (r"\bmaximize\b",           "get the most out of"),
    (r"\bMinimize\b",           "reduce"),
    (r"\bminimize\b",           "reduce"),
    (r"\bOptimize\b",           "improve"),
    (r"\boptimize\b",           "improve"),
    (r"\bPrioritize\b",         "focus on"),
    (r"\bprioritize\b",         "focus on"),
    (r"\bAccelerate\b",         "speed up"),
    (r"\baccelerate\b",         "speed up"),
    (r"\bAcknowledge\b",        "admit"),
    (r"\backnowledge\b",        "admit"),
    (r"\bAcquire\b",            "get"),
    (r"\bacquire\b",            "get"),
    (r"\bAdhere to\b",          "follow"),
    (r"\badhere to\b",          "follow"),
    (r"\bAdminister\b",         "run"),
    (r"\badminister\b",         "run"),
    (r"\bAllocate\b",           "set aside"),
    (r"\ballocate\b",           "set aside"),
    (r"\bAnticipate\b",         "expect"),
    (r"\banticipate\b",         "expect"),
    (r"\bApproximate\b",        "estimate"),
    (r"\bapproximate\b",        "estimate"),
    (r"\bAuthorize\b",          "allow"),
    (r"\bauthorize\b",          "allow"),
    (r"\bCategorize\b",         "group"),
    (r"\bcategorize\b",         "group"),
    (r"\bClassify\b",           "group"),
    (r"\bclassify\b",           "group"),
    (r"\bCollaborate\b",        "work together"),
    (r"\bcollaborate\b",        "work together"),
    (r"\bCompile\b",            "put together"),
    (r"\bcompile\b",            "put together"),
    (r"\bComprehend\b",         "understand"),
    (r"\bcomprehend\b",         "understand"),
    (r"\bConduct\b",            "do"),
    (r"\bconduct\b",            "do"),
    (r"\bConsolidate\b",        "combine"),
    (r"\bconsolidate\b",        "combine"),
    (r"\bConstruct\b",          "build"),
    (r"\bconstruct\b",          "build"),
    (r"\bContemplate\b",        "think about"),
    (r"\bcontemplate\b",        "think about"),
    (r"\bConvey\b",             "share"),
    (r"\bconvey\b",             "share"),
    (r"\bCoordinate\b",         "manage"),
    (r"\bcoordinate\b",         "manage"),
    (r"\bDetermine\b",          "figure out"),
    (r"\bdetermine\b",          "figure out"),
    (r"\bDisclose\b",           "share"),
    (r"\bdisclose\b",           "share"),
    (r"\bDisseminate\b",        "spread"),
    (r"\bdisseminate\b",        "spread"),
    (r"\bEffectuate\b",         "bring about"),
    (r"\beffectuate\b",         "bring about"),
    (r"\bEliminate\b",          "remove"),
    (r"\beliminate\b",          "remove"),
    (r"\bEmploy\b",             "use"),
    (r"\bemploy\b",             "use"),
    (r"\bEncourage\b",          "push"),
    (r"\bencourage\b",          "push"),
    (r"\bEndeavor\b",           "try"),
    (r"\bendeavor\b",           "try"),
    (r"\bEstablish\b",          "set up"),
    (r"\bestablish\b",          "set up"),
    (r"\bEvaluate\b",           "check"),
    (r"\bevaluate\b",           "check"),
    (r"\bExamine\b",            "look at"),
    (r"\bexamine\b",            "look at"),
    (r"\bExercise\b",           "use"),
    (r"\bexercise\b",           "use"),
    (r"\bExhibit\b",            "show"),
    (r"\bexhibit\b",            "show"),
    (r"\bExpedite\b",           "speed up"),
    (r"\bexpedite\b",           "speed up"),
    (r"\bFoster\b",             "grow"),
    (r"\bfoster\b",             "grow"),
    (r"\bGenerate\b",           "create"),
    (r"\bgenerate\b",           "create"),
    (r"\bIdentify\b",           "find"),
    (r"\bidentify\b",           "find"),
    (r"\bIncorporate\b",        "add"),
    (r"\bincorporate\b",        "add"),
    (r"\bIndicate\b",           "show"),
    (r"\bindicate\b",           "show"),
    (r"\bInitiate\b",           "start"),
    (r"\binitiate\b",           "start"),
    (r"\bInquire\b",            "ask"),
    (r"\binquire\b",            "ask"),
    (r"\bInvestigate\b",        "look into"),
    (r"\binvestigate\b",        "look into"),
    (r"\bMaintain\b",           "keep"),
    (r"\bmaintain\b",           "keep"),
    (r"\bModify\b",             "change"),
    (r"\bmodify\b",             "change"),
    (r"\bMonitor\b",            "track"),
    (r"\bmonitor\b",            "track"),
    (r"\bNegotiate\b",          "work out"),
    (r"\bnegotiate\b",          "work out"),
    (r"\bNotify\b",             "let know"),
    (r"\bnotify\b",             "let know"),
    (r"\bParticipate\b",        "take part"),
    (r"\bparticipate\b",        "take part"),
    (r"\bPerceive\b",           "see"),
    (r"\bperceive\b",           "see"),
    (r"\bPossess\b",            "have"),
    (r"\bpossess\b",            "have"),
    (r"\bProceed\b",            "go ahead"),
    (r"\bproceed\b",            "go ahead"),
    (r"\bProcure\b",            "get"),
    (r"\bprocure\b",            "get"),
    (r"\bRefrain from\b",       "avoid"),
    (r"\brefrain from\b",       "avoid"),
    (r"\bRemunerate\b",         "pay"),
    (r"\bremunerate\b",         "pay"),
    (r"\bReside\b",             "live"),
    (r"\breside\b",             "live"),
    (r"\bResolve\b",            "fix"),
    (r"\bresolve\b",            "fix"),
    (r"\bRetain\b",             "keep"),
    (r"\bretain\b",             "keep"),
    (r"\bReview\b",             "check"),
    (r"\breview\b",             "check"),
    (r"\bSeek\b",               "look for"),
    (r"\bseek\b",               "look for"),
    (r"\bSignify\b",            "mean"),
    (r"\bsignify\b",            "mean"),
    (r"\bSubmit\b",             "send"),
    (r"\bsubmit\b",             "send"),
    (r"\bSuffice\b",            "be enough"),
    (r"\bsuffice\b",            "be enough"),
    (r"\bSupport\b",            "back"),
    (r"\bsupport\b",            "back"),
    (r"\bTransform\b",          "change"),
    (r"\btransform\b",          "change"),
    (r"\bUndergo\b",            "go through"),
    (r"\bundergo\b",            "go through"),
    (r"\bUndertake\b",          "take on"),
    (r"\bundertake\b",          "take on"),
    (r"\bVerify\b",             "check"),
    (r"\bverify\b",             "check"),
    (r"\bYield\b",              "give"),
    (r"\byield\b",              "give"),

    # -----------------------------------------------------------------------
    # Formal nouns → casual
    # -----------------------------------------------------------------------
    (r"\bindividuals\b",        "people"),
    (r"\bIndividuals\b",        "People"),
    (r"\bresidence\b",          "home"),
    (r"\bResidence\b",          "Home"),
    (r"\bemployment\b",         "work"),
    (r"\bEmployment\b",         "Work"),
    (r"\bcompensation\b",       "pay"),
    (r"\bCompensation\b",       "Pay"),
    (r"\bremuneration\b",       "pay"),
    (r"\bRemuneration\b",       "Pay"),
    (r"\boccupation\b",         "job"),
    (r"\bOccupation\b",         "Job"),
    (r"\bprofession\b",         "job"),
    (r"\bProfession\b",         "Job"),
    (r"\bvocation\b",           "calling"),
    (r"\bVocation\b",           "Calling"),
    (r"\bdomicile\b",           "home"),
    (r"\bDomicile\b",           "Home"),
    (r"\bhabitation\b",         "home"),
    (r"\bHabitation\b",         "Home"),
    (r"\bdwelling\b",           "home"),
    (r"\bDwelling\b",           "Home"),
    (r"\bapartment\b",          "place"),
    (r"\bApartment\b",          "Place"),
    (r"\bvelocity\b",           "speed"),
    (r"\bVelocity\b",           "Speed"),
    (r"\bfrequency\b",          "rate"),
    (r"\bFrequency\b",          "Rate"),
    (r"\bproximity\b",          "nearness"),
    (r"\bProximity\b",          "Nearness"),
    (r"\bvicinity\b",           "area"),
    (r"\bVicinity\b",           "Area"),
    (r"\bchildren\b",           "kids"),
    (r"\bChildren\b",           "Kids"),
    (r"\bphysician\b",          "doctor"),
    (r"\bPhysician\b",          "Doctor"),
    (r"\brepository\b",         "store"),
    (r"\bRepository\b",         "Store"),
    (r"\bcommencement\b",       "start"),
    (r"\bCommencement\b",       "Start"),
    (r"\btermination\b",        "end"),
    (r"\bTermination\b",        "End"),
    (r"\binquiry\b",            "question"),
    (r"\bInquiry\b",            "Question"),
    (r"\bcorrespondence\b",     "message"),
    (r"\bCorrespondence\b",     "Message"),
    (r"\bdocumentation\b",      "docs"),
    (r"\bDocumentation\b",      "Docs"),
    (r"\bperformance\b",        "results"),
    (r"\bPerformance\b",        "Results"),
    (r"\bapproximation\b",      "estimate"),
    (r"\bApproximation\b",      "Estimate"),
    (r"\bcalculation\b",        "estimate"),
    (r"\bCalculation\b",        "Estimate"),
    (r"\bconfiguration\b",      "setup"),
    (r"\bConfiguration\b",      "Setup"),
    (r"\bfunctionality\b",      "features"),
    (r"\bFunctionality\b",      "Features"),
    (r"\bvisibility\b",         "exposure"),
    (r"\bVisibility\b",         "Exposure"),
    (r"\bflexibility\b",        "room to adapt"),
    (r"\bFlexibility\b",        "Room to adapt"),
    (r"\bscalability\b",        "room to grow"),
    (r"\bScalability\b",        "Room to grow"),

    # -----------------------------------------------------------------------
    # Redundant qualifiers AI loves
    # -----------------------------------------------------------------------
    (r"\bvery unique\b",                "unique"),
    (r"\bVery unique\b",                "Unique"),
    (r"\babsolutely essential\b",       "essential"),
    (r"\bAbsolutely essential\b",       "Essential"),
    (r"\babsolutely necessary\b",       "necessary"),
    (r"\bAbsolutely necessary\b",       "Necessary"),
    (r"\bcompletely eliminate\b",       "eliminate"),
    (r"\bCompletely eliminate\b",       "Eliminate"),
    (r"\bcompletely free\b",            "free"),
    (r"\bCompletely free\b",            "Free"),
    (r"\bcompletely different\b",       "different"),
    (r"\bCompletely different\b",       "Different"),
    (r"\bcompletely new\b",             "new"),
    (r"\bCompletely new\b",             "New"),
    (r"\bfully complete\b",             "complete"),
    (r"\bFully complete\b",             "Complete"),
    (r"\bactually true\b",              "true"),
    (r"\bActually true\b",              "True"),
    (r"\btotally wrong\b",              "wrong"),
    (r"\bTotally wrong\b",              "Wrong"),
    (r"\bvery important\b",             "important"),
    (r"\bVery important\b",             "Important"),
    (r"\bvery significant\b",           "significant"),
    (r"\bVery significant\b",           "Significant"),
    (r"\bvery crucial\b",               "crucial"),
    (r"\bVery crucial\b",               "Crucial"),
    (r"\bbasically\b",                  ""),
    (r"\bessentially\b",                ""),
    (r"\bfundamentally\b",              ""),
    (r"\bultimately\b",                 "in the end"),
    (r"\bUltimately\b",                 "In the end"),
    (r"\bin essence\b",                 "at its core"),
    (r"\bIn essence\b",                 "At its core"),
    (r"\bin practice\b",                "in reality"),
    (r"\bIn practice\b",                "In reality"),
    (r"\bin reality\b",                 "actually"),
    (r"\bIn reality\b",                 "Actually"),
    (r"\bIn actuality\b",               "Actually"),
    (r"\bin actuality\b",               "actually"),
    (r"\bIn fact\b",                    "Actually"),
    (r"\bin fact\b",                    "actually"),
    (r"\bAs a matter of fact\b",        "Actually"),
    (r"\bas a matter of fact\b",        "actually"),
    (r"\bTo tell the truth\b",          "Honestly"),
    (r"\bto tell the truth\b",          "honestly"),
    (r"\bTo be honest\b",               "Honestly"),
    (r"\bto be honest\b",               "honestly"),
    (r"\bTo be frank\b",                "Honestly"),
    (r"\bto be frank\b",                "honestly"),
    (r"\bTo be candid\b",               "Honestly"),
    (r"\bto be candid\b",               "honestly"),
    (r"\bTo be straightforward\b",      "Honestly"),
    (r"\bto be straightforward\b",      "honestly"),
    (r"\bSimply put\b",                 "Put simply"),
    (r"\bPut simply\b",                 "Put simply"),
    (r"\bIn simple terms\b",            "Simply put"),
    (r"\bin simple terms\b",            "simply put"),
    (r"\bIn layman's terms\b",          "Simply put"),
    (r"\bin layman's terms\b",          "simply put"),
    (r"\bin a nutshell\b",              "in short"),
    (r"\bIn a nutshell\b",              "In short"),
    (r"\bat the end of the day\b",      "ultimately"),
    (r"\bAt the end of the day\b",      "Ultimately"),
    (r"\bwhen all is said and done\b",  "ultimately"),
    (r"\bWhen all is said and done\b",  "Ultimately"),
]

# ---------------------------------------------------------------------------
# Passive voice → active rewrites
# ---------------------------------------------------------------------------
_PASSIVE_REWRITES: List[Tuple[str, str]] = [
    (r"\bit can be seen that\b",            "we can see that"),
    (r"\bIt can be seen that\b",            "We can see that"),
    (r"\bit can be argued that\b",          "you could argue that"),
    (r"\bIt can be argued that\b",          "You could argue that"),
    (r"\bit can be said that\b",            "you could say that"),
    (r"\bIt can be said that\b",            "You could say that"),
    (r"\bit has been shown that\b",         "research shows that"),
    (r"\bIt has been shown that\b",         "Research shows that"),
    (r"\bit has been found that\b",         "studies found that"),
    (r"\bIt has been found that\b",         "Studies found that"),
    (r"\bit is believed that\b",            "many believe that"),
    (r"\bIt is believed that\b",            "Many believe that"),
    (r"\bit is suggested that\b",           "the data suggests that"),
    (r"\bIt is suggested that\b",           "The data suggests that"),
    (r"\bit is recommended that\b",         "we recommend that"),
    (r"\bIt is recommended that\b",         "We recommend that"),
    (r"\bit is expected that\b",            "we expect that"),
    (r"\bIt is expected that\b",            "We expect that"),
    (r"\bit is assumed that\b",             "we assume that"),
    (r"\bIt is assumed that\b",             "We assume that"),
    (r"\bit is acknowledged that\b",        "we acknowledge that"),
    (r"\bIt is acknowledged that\b",        "We acknowledge that"),
    (r"\bshould be noted\b",                "worth noting"),
    (r"\bshould be mentioned\b",            "worth mentioning"),
    (r"\bmust be considered\b",             "we need to consider"),
    (r"\bit can be observed that\b",        "we can observe that"),
    (r"\bIt can be observed that\b",        "We can observe that"),
    (r"\bit can be concluded that\b",       "we can conclude that"),
    (r"\bIt can be concluded that\b",       "We can conclude that"),
    (r"\bit can be inferred that\b",        "we can infer that"),
    (r"\bIt can be inferred that\b",        "We can infer that"),
    (r"\bit can be noted that\b",           "it's worth noting that"),
    (r"\bIt can be noted that\b",           "It's worth noting that"),
    (r"\bit can be stated that\b",          "you could say that"),
    (r"\bIt can be stated that\b",          "You could say that"),
    (r"\bit may be argued that\b",          "you could argue that"),
    (r"\bIt may be argued that\b",          "You could argue that"),
    (r"\bit may be said that\b",            "you could say that"),
    (r"\bIt may be said that\b",            "You could say that"),
    (r"\bit may be noted that\b",           "worth noting:"),
    (r"\bIt may be noted that\b",           "Worth noting:"),
    (r"\bit is known that\b",               "we know that"),
    (r"\bIt is known that\b",               "We know that"),
    (r"\bit is understood that\b",          "we understand that"),
    (r"\bIt is understood that\b",          "We understand that"),
    (r"\bit is generally accepted that\b",  "most people agree that"),
    (r"\bIt is generally accepted that\b",  "Most people agree that"),
    (r"\bit is widely accepted that\b",     "most people accept that"),
    (r"\bIt is widely accepted that\b",     "Most people accept that"),
    (r"\bit is recognized that\b",          "we recognize that"),
    (r"\bIt is recognized that\b",          "We recognize that"),
    (r"\bit is generally agreed that\b",    "most agree that"),
    (r"\bIt is generally agreed that\b",    "Most agree that"),
    (r"\bit is often said that\b",          "people often say that"),
    (r"\bIt is often said that\b",          "People often say that"),
    (r"\bit has been argued that\b",        "some have argued that"),
    (r"\bIt has been argued that\b",        "Some have argued that"),
    (r"\bit has been suggested that\b",     "some have suggested that"),
    (r"\bIt has been suggested that\b",     "Some have suggested that"),
    (r"\bit has been demonstrated that\b",  "studies show that"),
    (r"\bIt has been demonstrated that\b",  "Studies show that"),
    (r"\bit has been established that\b",   "we've established that"),
    (r"\bIt has been established that\b",   "We've established that"),
    (r"\bit has been reported that\b",      "reports show that"),
    (r"\bIt has been reported that\b",      "Reports show that"),
    (r"\bit has been observed that\b",      "we've observed that"),
    (r"\bIt has been observed that\b",      "We've observed that"),
    (r"\bit has been noted that\b",         "we've noted that"),
    (r"\bIt has been noted that\b",         "We've noted that"),
    (r"\bshould be emphasized\b",           "worth stressing"),
    (r"\bshould be highlighted\b",          "worth highlighting"),
    (r"\bshould be stressed\b",             "worth stressing"),
    (r"\bmust be acknowledged\b",           "we have to acknowledge"),
    (r"\bmust be noted\b",                  "we must note"),
    (r"\bmust be recognized\b",             "we have to recognize"),
    (r"\bcan be seen as\b",                 "looks like"),
    (r"\bCan be seen as\b",                 "Looks like"),
    (r"\bcould be seen as\b",               "might look like"),
    (r"\bCould be seen as\b",               "Might look like"),
    (r"\bhas been shown to\b",              "appears to"),
    (r"\bHas been shown to\b",              "Appears to"),
    (r"\bhave been shown to\b",             "appear to"),
    (r"\bHave been shown to\b",             "Appear to"),
    (r"\bis considered to be\b",            "is seen as"),
    (r"\bIs considered to be\b",            "Is seen as"),
    (r"\bare considered to be\b",           "are seen as"),
    (r"\bAre considered to be\b",           "Are seen as"),
    (r"\bis thought to be\b",               "seems to be"),
    (r"\bIs thought to be\b",               "Seems to be"),
    (r"\bare thought to be\b",              "seem to be"),
    (r"\bAre thought to be\b",              "Seem to be"),
]

_HUMAN_OPENERS = [
    "Honestly,",
    "Here's the thing —",
    "Think about it:",
    "To be fair,",
    "The short answer is",
    "Interestingly enough,",
    "You might be surprised, but",
    "Real talk —",
    "And honestly?",
    "Here's what matters:",
    "Worth saying:",
    "Look —",
    "No surprise there:",
    "Funny enough,",
    "Truth is,",
    "And here's where it gets interesting:",
    "You know what?",
    "Here's the kicker:",
    "Not gonna lie,",
    "What you need to know is",
    "Between you and me,",
    "Here's the deal:",
    "Let me be real:",
    "And this is key:",
    "Here's the part most people miss:",
    "Believe it or not,",
    "Plot twist:",
    "Fair warning:",
    "And don't overlook this:",
    "So here's the thing:",
    "At the end of the day,",
    "Bottom line:",
    "The thing is,",
    "Worth knowing:",
    "Quick note:",
    "Here's a thought:",
    "Just to be clear,",
    "Good news:",
    "Here's my take:",
    "Spoiler:",
    "To put it plainly,",
]


class TextTransformer:
    """
    Applies a configurable pipeline of transformations to a text string.
    Each pass is isolated and toggleable. Transforms run in order so
    later passes do not undo earlier ones.
    """

    def __init__(
        self,
        use_contractions: bool = True,
        simplify_formal: bool = True,
        vary_sentences: bool = True,
        rewrite_passive: bool = True,
        seed: int | None = None,
    ):
        self.use_contractions = use_contractions
        self.simplify_formal = simplify_formal
        self.vary_sentences = vary_sentences
        self.rewrite_passive = rewrite_passive
        self._rng = random.Random(seed)

    def transform(self, text: str) -> str:
        if not text or not text.strip():
            return text

        result = text

        if self.rewrite_passive:
            result = self._apply_passive_rewrites(result)

        if self.simplify_formal:
            result = self._apply_formal_simplification(result)

        if self.use_contractions:
            result = self._apply_contractions(result)

        if self.vary_sentences:
            result = self._apply_sentence_variation(result)

        result = self._clean_up(result)
        return result

    # ------------------------------------------------------------------
    # Transformation passes
    # ------------------------------------------------------------------

    def _apply_contractions(self, text: str) -> str:
        for pattern, replacement in _CONTRACTION_EXPAND.items():
            text = re.sub(pattern, replacement, text)
        return text

    def _apply_formal_simplification(self, text: str) -> str:
        for pattern, replacement in _FORMAL_TO_CASUAL:
            text = re.sub(pattern, replacement, text)
        return text

    def _apply_passive_rewrites(self, text: str) -> str:
        for pattern, replacement in _PASSIVE_REWRITES:
            text = re.sub(pattern, replacement, text)
        return text

    def _apply_sentence_variation(self, text: str) -> str:
        sentences = re.split(r"(?<=[.!?])\s+", text)
        if len(sentences) < 4:
            return text

        result_parts = []
        for i, sent in enumerate(sentences):
            if i > 0 and i % 5 == 0 and re.match(r"^(The|This)\b", sent):
                opener = self._rng.choice(_HUMAN_OPENERS)
                sent = f"{opener} {sent[0].lower()}{sent[1:]}"
            result_parts.append(sent)

        return " ".join(result_parts)

    @staticmethod
    def _clean_up(text: str) -> str:
        # Fix double spaces from empty-string replacements (e.g. "basically" → "")
        text = re.sub(r" {2,}", " ", text)
        # Fix artifact commas like "So, ,"
        text = re.sub(r",\s*,", ",", text)
        # Fix space before period
        text = re.sub(r"\s+\.", ".", text)
        # Fix leading space after newlines
        text = re.sub(r"\n ", "\n", text)
        return text.strip()